name: Generate members

on:
  push:
    branches:
      - main
    paths:
      - 'members.yaml'

jobs:
  generate-members:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: codingpot/github-org-member-manage-action@v1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          members_filepath: members.yaml
          mode: write

      - uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write {*,**/*}.{md,yml,yaml}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Refresh members.yaml from GitHub
          reviewers: dojinyou